// 此清单基于固定上游提交逐文件核对。一个候选可以覆盖同一规则中的多个同义词，
// 也可以覆盖同一文件内语义相同的一组规则；但每个含已加载规则的源码文件都必须
// 有明确映射。scripts/check.mjs 会验证规则总数、文件映射与候选 ID，防止后续误删。

export const UPSTREAM_COMMAND_AUDIT = {
  miao: {
    repository: "yoimiya-kokomi/miao-plugin",
    commit: "1eaef54",
    staticRuleCount: 59,
    dynamicPaths: [
      { source: "apps/character/AvatarCard.js#check", coveredBy: ["miao.character_card"] },
      { source: "apps/wiki/CharWiki.js#check", coveredBy: ["miao.character_wiki"] },
    ],
    files: [
      {
        source: "apps/admin.js",
        rules: 5,
        coveredBy: ["miao.resource_update", "miao.resource_force_update", "miao.plugin_update", "miao.plugin_force_update", "miao.update_log", "miao.settings", "miao.api_info"],
      },
      { source: "apps/alias.js", rules: 10, coveredBy: ["miao.alias_help", "miao.alias_set", "miao.alias_delete", "miao.alias_list"] },
      { source: "apps/character.js", rules: 4, coveredBy: ["miao.character_card", "miao.character_image_upload", "miao.relationship_card", "miao.relationship_set", "miao.original_image"] },
      { source: "apps/gacha.js", rules: 2, coveredBy: ["miao.gacha_summary"] },
      { source: "apps/help.js", rules: 2, coveredBy: ["miao.help", "miao.version"] },
      {
        source: "apps/profile.js",
        rules: 23,
        coveredBy: [
          "miao.profile_list", "miao.profile_detail", "miao.profile_change", "miao.group_best_profile",
          "miao.group_rank_reset", "miao.group_rank_refresh", "miao.group_rank_enable", "miao.group_rank_disable",
          "miao.group_rank_list", "miao.artifact_list", "miao.profile_stats", "miao.theater_role_stats",
          "miao.talent_stats", "miao.avatar_list", "miao.talent_refresh", "miao.panel_help", "miao.enemy_level",
          "miao.profile_refresh", "miao.mys_profile_refresh", "miao.panel_image_upload", "miao.panel_image_delete",
          "miao.panel_image_list", "miao.profile_delete", "miao.profile_reload",
        ],
      },
      { source: "apps/stat.js", rules: 8, coveredBy: ["miao.character_ownership", "miao.abyss_usage", "miao.abyss_teams", "miao.abyss_data", "miao.theater_data", "miao.theater_card_collection", "miao.theater_card_exchange", "miao.stygian_data"] },
      { source: "apps/wiki.js", rules: 5, coveredBy: ["miao.wiki_help", "miao.character_wiki", "miao.genshin_calendar", "miao.starrail_calendar", "miao.zzz_calendar", "miao.today_material"] },
    ],
  },
  genshin: {
    repository: "TimeRainStarSky/Yunzai-genshin",
    commit: "4a2e1fb",
    staticRuleCount: 67,
    dynamicPaths: [
      { source: "apps/role.js#accept", coveredBy: ["genshin.character_detail"] },
      { source: "apps/user.js#accept", coveredBy: ["genshin.cookie_payload", "genshin.bind_uid", "starrail.bind_uid", "zzz.bind_uid"] },
      { source: "apps/gcLog.js#accept", coveredBy: ["genshin.gacha_records"] },
    ],
    files: [
      { source: "apps/abbrSet.js", rules: 3, coveredBy: ["genshin.alias_set", "genshin.alias_delete", "genshin.alias_lookup"] },
      { source: "apps/buddy.js", rules: 1, coveredBy: ["zzz.bangboo"] },
      { source: "apps/calculator.js", rules: 4, coveredBy: ["genshin.character_development", "starrail.development_help", "genshin.development_help", "genshin.blueprint", "genshin.blueprint_help"] },
      { source: "apps/dailyNote.js", rules: 1, coveredBy: ["xiaoyao.stamina", "starrail.sanity"] },
      { source: "apps/exchange.js", rules: 2, coveredBy: ["genshin.redemption_codes", "starrail.redemption_codes", "zzz.redemption_codes", "hoyo.redemption_codes", "genshin.redeem_code"] },
      { source: "apps/gacha.js", rules: 2, coveredBy: ["genshin.simulate_gacha", "genshin.weapon_course"] },
      { source: "apps/gcLog.js", rules: 8, coveredBy: ["genshin.gacha_authkey_link", "genshin.gacha_import_options", "genshin.gacha_records", "genshin.gacha_export_options", "genshin.gacha_help", "genshin.gacha_platform_help", "genshin.gacha_full_update_setting"] },
      { source: "apps/ledger.js", rules: 4, coveredBy: ["genshin.ledger", "genshin.ledger_month", "genshin.ledger_task", "genshin.ledger_stats", "genshin.ledger_history"] },
      { source: "apps/material.js", rules: 1, coveredBy: ["genshin.character_materials"] },
      { source: "apps/mysNews.js", rules: 7, coveredBy: ["genshin.announcements", "starrail.announcements", "zzz.announcements", "hoyo.news", "hoyo.news_search", "hoyo.article_link", "genshin.news_estimate", "hoyo.news_push_toggle", "hoyo.news_push_now", "hoyo.expiring_event_push"] },
      { source: "apps/noteZzz.js", rules: 1, coveredBy: ["zzz.sanity"] },
      { source: "apps/payLog.js", rules: 4, coveredBy: ["genshin.payment_records", "genshin.payment_records_update", "genshin.payment_link", "genshin.payment_help"] },
      { source: "apps/role.js", rules: 6, coveredBy: ["genshin.role_card", "genshin.abyss", "genshin.abyss_floor", "genshin.weapon_list", "genshin.weapon_list_filtered", "genshin.exploration", "genshin.exploration_category", "genshin.theater"] },
      { source: "apps/setPubCk.js", rules: 2, coveredBy: ["genshin.public_cookie_config", "genshin.use_all_cookie", "genshin.use_user_cookie"] },
      { source: "apps/sevenSaints.js", rules: 2, coveredBy: ["genshin.seven_saints_decks", "genshin.seven_saints_cards"] },
      { source: "apps/strategy.js", rules: 3, coveredBy: ["genshin.guide", "genshin.guide_refresh", "genshin.strategy_help", "genshin.guide_default_source"] },
      { source: "apps/takeBirthdayPhoto.js", rules: 1, coveredBy: ["genshin.birthday_card"] },
      { source: "apps/user.js", rules: 12, coveredBy: ["genshin.cookie_help", "genshin.cookie_code", "genshin.cookie_bind", "genshin.mhyuuid_payload", "genshin.cookie_show", "genshin.cookie_delete", "genshin.uid_delete", "genshin.bind_uid", "starrail.bind_uid", "zzz.bind_uid", "genshin.show_uid", "starrail.show_uid", "zzz.show_uid", "genshin.cookie_status", "genshin.linked_account_bind", "genshin.linked_account_unbind"] },
      { source: "apps/userAdmin.js", rules: 3, coveredBy: ["genshin.user_stats", "genshin.user_cache_refresh", "genshin.invalid_users_delete"] },
    ],
  },
  starrail: {
    repository: "TsukinaKasumi/StarRail-plugin",
    commit: "090e411",
    staticRuleCount: 54,
    dynamicPaths: [],
    files: [
      { source: "apps/MiaoOrStarrail.js", rules: 3, coveredBy: ["miao.profile_refresh", "miao.profile_detail", "starrail.panel_plugin_toggle"] },
      { source: "apps/alias.js", rules: 3, coveredBy: ["starrail.alias_set", "starrail.alias_delete", "starrail.alias_lookup"] },
      { source: "apps/challenge.js", rules: 6, coveredBy: ["starrail.challenge_overview", "starrail.challenge"] },
      { source: "apps/gachasimulation.js", rules: 1, coveredBy: ["starrail.gacha_simulation"] },
      { source: "apps/gatcha.js", rules: 4, coveredBy: ["starrail.gacha_link", "starrail.gacha_records", "starrail.gacha_help", "starrail.gacha_update"] },
      { source: "apps/gridFight.js", rules: 2, coveredBy: ["starrail.currency_war"] },
      { source: "apps/help.js", rules: 1, coveredBy: ["starrail.help"] },
      { source: "apps/hkrpg.js", rules: 4, coveredBy: ["starrail.bind_uid", "starrail.card", "starrail.account_card", "starrail.account_records", "starrail.online_stats"] },
      { source: "apps/month.js", rules: 1, coveredBy: ["starrail.monthly_income"] },
      { source: "apps/note.js", rules: 1, coveredBy: ["starrail.sanity"] },
      { source: "apps/panel.js", rules: 6, coveredBy: ["miao.profile_detail", "miao.profile_list", "miao.profile_refresh", "starrail.panel_api_select", "starrail.api_list", "miao.original_image"] },
      { source: "apps/rogue.js", rules: 8, coveredBy: ["starrail.simulated_universe", "starrail.divergent_universe", "starrail.rogue_mode"] },
      { source: "apps/srxx.js", rules: 8, coveredBy: ["starrail.reference_panel", "starrail.reference_panel_help", "starrail.return_curve", "starrail.strength_rank", "starrail.strategy_overview", "starrail.resource_estimate", "starrail.abyss_guide", "starrail.shop_lightcone_recommendation"] },
      { source: "apps/strategy.js", rules: 3, coveredBy: ["starrail.guide", "starrail.guide_refresh", "starrail.strategy_help", "starrail.guide_default_source"] },
      { source: "apps/update.js", rules: 2, coveredBy: ["starrail.plugin_update", "starrail.plugin_force_update", "starrail.image_update", "starrail.image_force_update"] },
      { source: "apps/version.js", rules: 1, coveredBy: ["starrail.update_log"] },
    ],
  },
  waves: {
    repository: "ziyiLike/waves-plugin",
    commit: "64f24d3",
    staticRuleCount: 139,
    dynamicPaths: [],
    files: [
      { source: "apps/Alias.js", rules: 3, coveredBy: ["waves.alias_set", "waves.alias_delete", "waves.alias_lookup"] },
      { source: "apps/Bind.js", rules: 4, coveredBy: ["waves.bind_code", "waves.login", "waves.login_delete", "waves.token_show"] },
      { source: "apps/Calabash.js", rules: 1, coveredBy: ["waves.data_bank"] },
      { source: "apps/Calendar.js", rules: 1, coveredBy: ["waves.calendar", "waves.current_pool"] },
      { source: "apps/Challenge.js", rules: 1, coveredBy: ["waves.challenge"] },
      { source: "apps/Character.js", rules: 1, coveredBy: ["waves.profile"] },
      { source: "apps/CharacterInfo.js", rules: 3, coveredBy: ["waves.character_info", "waves.character_english_name"] },
      { source: "apps/CharacterMAX.js", rules: 1, coveredBy: ["waves.character_max_profile"] },
      { source: "apps/CharacterRe.js", rules: 1, coveredBy: ["waves.echo_replace"] },
      { source: "apps/CharacterScore.js", rules: 1, coveredBy: ["waves.character_score"] },
      { source: "apps/Chiyoulv.js", rules: 2, coveredBy: ["waves.character_ownership", "waves.character_ownership_scope"] },
      { source: "apps/CloudGacha.js", rules: 4, coveredBy: ["waves.cloud_login", "waves.gacha_update", "waves.cloud_login_delete", "waves.gacha_link_show"] },
      { source: "apps/EchoInfo.js", rules: 3, coveredBy: ["waves.echo_search", "waves.harmony_info"] },
      { source: "apps/Emoji.js", rules: 1, coveredBy: ["waves.emoji"] },
      { source: "apps/EncoreSync.js", rules: 15, coveredBy: ["waves.encore_resources"] },
      { source: "apps/Explore.js", rules: 1, coveredBy: ["waves.explore"] },
      { source: "apps/FotgInfo.js", rules: 6, coveredBy: ["waves.fotg_schedule", "waves.fotg_schedule_full", "waves.fotg_cache_clear"] },
      { source: "apps/Fuke.js", rules: 3, coveredBy: ["waves.rerun_prediction"] },
      { source: "apps/Gacha.js", rules: 3, coveredBy: ["waves.gacha_records", "waves.gacha_payload", "waves.gacha_import", "waves.gacha_export"] },
      { source: "apps/Guide.js", rules: 1, coveredBy: ["waves.atlas"] },
      { source: "apps/HaixuRanking.js", rules: 6, coveredBy: ["waves.haixu_ranking", "waves.challenge_ranking_setting"] },
      { source: "apps/Help.js", rules: 3, coveredBy: ["waves.help", "waves.login_help", "waves.gacha_help"] },
      { source: "apps/Manage.js", rules: 2, coveredBy: ["waves.user_stats", "waves.invalid_users_delete"] },
      { source: "apps/MatrixRanking.js", rules: 6, coveredBy: ["waves.matrix_ranking", "waves.challenge_ranking_setting"] },
      { source: "apps/MonsterInfo.js", rules: 2, coveredBy: ["waves.monster_info"] },
      { source: "apps/MyEchoList.js", rules: 1, coveredBy: ["waves.echo_inventory"] },
      { source: "apps/NamecardInfo.js", rules: 2, coveredBy: ["waves.namecard_info"] },
      { source: "apps/News.js", rules: 1, coveredBy: ["waves.news"] },
      { source: "apps/Paiming.js", rules: 5, coveredBy: ["waves.character_ranking", "waves.ranking_data_sync", "waves.ranking_setting"] },
      { source: "apps/Reward.js", rules: 1, coveredBy: ["waves.redemption_codes"] },
      { source: "apps/Sanity.js", rules: 1, coveredBy: ["waves.sanity"] },
      { source: "apps/Setting.js", rules: 5, coveredBy: ["waves.enable_auto_sign", "waves.disable_auto_sign", "waves.enable_auto_task", "waves.disable_auto_task", "waves.stamina_push", "waves.news_push", "waves.stamina_threshold"] },
      { source: "apps/Shock.js", rules: 1, coveredBy: ["waves.shock_simulation"] },
      { source: "apps/SignIn.js", rules: 3, coveredBy: ["waves.sign", "waves.sign_records", "waves.sign_all"] },
      { source: "apps/Simulator.js", rules: 6, coveredBy: ["waves.gacha_simulation", "waves.gacha_resource_update", "waves.gacha_pity_reset", "waves.gacha_pool_switch", "waves.gacha_pool_view"] },
      { source: "apps/Strategy.js", rules: 1, coveredBy: ["waves.guide"] },
      { source: "apps/Task.js", rules: 3, coveredBy: ["waves.daily_task", "waves.task_list", "waves.task_all"] },
      { source: "apps/TitleInfo.js", rules: 2, coveredBy: ["waves.title_info"] },
      { source: "apps/Tower.js", rules: 1, coveredBy: ["waves.tower"] },
      { source: "apps/TowerInfo.js", rules: 2, coveredBy: ["waves.tower_schedule", "waves.tower_schedule_full", "waves.tower_cache_clear"] },
      { source: "apps/Training.js", rules: 1, coveredBy: ["waves.training"] },
      { source: "apps/Update.js", rules: 1, coveredBy: ["waves.plugin_update", "waves.plugin_force_update"] },
      { source: "apps/User.js", rules: 1, coveredBy: ["waves.card"] },
      { source: "apps/WeaponInfo.js", rules: 2, coveredBy: ["waves.weapon_info"] },
      { source: "apps/WeightView.js", rules: 2, coveredBy: ["waves.score_weight"] },
      { source: "apps/Xingsheng.js", rules: 1, coveredBy: ["waves.resource_report", "waves.resource_report_period"] },
      { source: "apps/cos.js", rules: 3, coveredBy: ["waves.cosplay", "waves.cosplay_cache_clear"] },
      { source: "apps/imgUpload.js", rules: 4, coveredBy: ["waves.panel_image_upload", "waves.original_image", "waves.panel_image_list", "waves.panel_image_delete"] },
      { source: "apps/newTowerDeta.js", rules: 1, coveredBy: ["waves.matrix"] },
      { source: "apps/newTowerDetaInfo.js", rules: 6, coveredBy: ["waves.matrix_schedule", "waves.matrix_schedule_full", "waves.matrix_cache_clear"] },
      { source: "apps/slash.js", rules: 1, coveredBy: ["waves.haixu"] },
      { source: "apps/slashInfo.js", rules: 6, coveredBy: ["waves.haixu_schedule", "waves.haixu_schedule_full", "waves.haixu_cache_clear"] },
    ],
  },
  xiaoyao: {
    repository: "Ctrlcvs/xiaoyao-cvs-plugin",
    commit: "e7ab3e8",
    staticRuleCount: 34,
    dynamicPaths: [],
    files: [
      { source: "apps/admin.js", rules: 4, coveredBy: ["xiaoyao.resource_update", "xiaoyao.resource_force_update", "xiaoyao.plugin_update", "xiaoyao.plugin_force_update", "xiaoyao.template_update", "xiaoyao.template_force_update", "xiaoyao.settings"] },
      { source: "apps/index.js", rules: 9, coveredBy: ["xiaoyao.version", "xiaoyao.help", "xiaoyao.atlas", "xiaoyao.stamina", "xiaoyao.stamina_push", "xiaoyao.stamina_template", "xiaoyao.poke_stamina", "xiaoyao.character_video"] },
      { source: "apps/map.js", rules: 2, coveredBy: ["xiaoyao.map_location", "xiaoyao.map_cache_clear"] },
      { source: "apps/mhyTopUpLogin.js", rules: 4, coveredBy: ["xiaoyao.qr_login", "xiaoyao.password_login", "xiaoyao.password_payload", "xiaoyao.topup"] },
      { source: "apps/sign.js", rules: 6, coveredBy: ["xiaoyao.genshin_sign", "xiaoyao.starrail_sign", "xiaoyao.zzz_sign", "xiaoyao.game_sign", "xiaoyao.community_sign", "xiaoyao.cloud_genshin_sign", "xiaoyao.currency_status", "xiaoyao.cloud_genshin_status", "xiaoyao.account_help", "xiaoyao.account_help_full", "xiaoyao.sign_all"] },
      { source: "apps/user.js", rules: 9, coveredBy: ["xiaoyao.user_info", "xiaoyao.gacha_update", "xiaoyao.gacha_export", "xiaoyao.payment_records", "xiaoyao.token_show", "xiaoyao.stoken_payload", "xiaoyao.login_ticket_payload", "xiaoyao.cloud_token_payload", "xiaoyao.credential_delete", "xiaoyao.cookie_refresh"] },
    ],
  },
}

export const AUDITED_STATIC_RULE_COUNT = Object.values(UPSTREAM_COMMAND_AUDIT)
  .reduce((total, plugin) => total + plugin.staticRuleCount, 0)

export const AUDITED_DYNAMIC_PATH_COUNT = Object.values(UPSTREAM_COMMAND_AUDIT)
  .reduce((total, plugin) => total + plugin.dynamicPaths.length, 0)
