export const DEFAULT_MEMORY_TURNS = 20
export const LEGACY_DEFAULT_MEMORY_MESSAGES = 8
export const GUIDE_AUTO_EXECUTE_IDS = ["genshin.guide", "starrail.guide"]

// 上一版随项目发布的完整默认白名单。只在用户仍原样使用这份列表时，才自动
// 补充本次命令审计新增的只读候选，避免扩大管理员自行收窄过的执行范围。
export const PRE_COMMAND_AUDIT_AUTO_EXECUTE_ALLOWLIST = [
  "miao.help",
  "miao.genshin_calendar",
  "miao.starrail_calendar",
  "miao.zzz_calendar",
  "miao.today_material",
  "miao.profile_list",
  "miao.profile_detail",
  "genshin.guide",
  "starrail.guide",
  "miao.profile_stats",
  "miao.gacha_summary",
  "miao.character_ownership",
  "miao.abyss_usage",
  "miao.abyss_teams",
  "miao.abyss_data",
  "miao.theater_data",
  "miao.stygian_data",
  "waves.help",
  "waves.login_help",
  "waves.sanity",
  "waves.card",
  "waves.explore",
  "waves.challenge",
  "waves.tower",
  "waves.profile",
  "waves.guide",
  "waves.atlas",
  "waves.calendar",
  "waves.news",
  "waves.gacha_records",
  "waves.data_bank",
  "waves.training",
  "waves.sign_records",
  "waves.redemption_codes",
  "waves.resource_report",
  "waves.character_ownership",
  "xiaoyao.help",
  "xiaoyao.version",
  "xiaoyao.stamina",
  "xiaoyao.atlas",
  "xiaoyao.map_location",
  "xiaoyao.account_help",
]

export const COMMAND_AUDIT_AUTO_EXECUTE_IDS = [
  "miao.version",
  "miao.panel_help",
  "genshin.show_uid",
  "starrail.show_uid",
  "zzz.show_uid",
  "genshin.role_card",
  "genshin.exploration",
  "genshin.abyss",
  "genshin.theater",
  "genshin.ledger",
  "genshin.development_help",
  "genshin.announcements",
  "genshin.redemption_codes",
  "zzz.sanity",
  "zzz.announcements",
  "zzz.redemption_codes",
  "starrail.help",
  "starrail.sanity",
  "starrail.monthly_income",
  "starrail.card",
  "starrail.online_stats",
  "starrail.gacha_help",
  "starrail.gacha_records",
  "starrail.challenge_overview",
  "starrail.simulated_universe",
  "starrail.divergent_universe",
  "starrail.strength_rank",
  "starrail.development_help",
  "starrail.announcements",
  "starrail.redemption_codes",
  "waves.task_list",
  "waves.gacha_help",
  "waves.tower_schedule",
  "waves.haixu",
  "waves.haixu_schedule",
  "waves.matrix",
  "waves.matrix_schedule",
  "waves.fotg_schedule",
  "waves.echo_inventory",
  "xiaoyao.currency_status",
]

export const DEFAULT_CONFIG = {
  enabled: true,
  trigger: {
    privateEnabled: true,
    requireAtInGroup: true,
    allowAliasInGroup: true,
    enabledGroups: [],
    disabledGroups: [],
  },
  api: {
    baseUrl: "https://api.openai.com/v1",
    endpoint: "/chat/completions",
    apiKey: "",
    apiKeyEnv: "OPENAI_API_KEY",
    allowUnauthenticated: false,
    allowInsecureHttp: false,
    model: "",
    timeoutMs: 20_000,
    retries: 1,
    temperature: 0.2,
    maxTokens: 900,
    maxTokensField: "max_tokens",
    responseFormat: "auto",
    extraHeaders: {},
  },
  vision: {
    enabled: true,
    maxImages: 3,
    maxBytesPerImage: 5_242_880,
    timeoutMs: 10_000,
    detail: "auto",
    allowInsecureHttp: false,
  },
  knowledge: {
    enabled: true,
    guideVisionEnabled: true,
    model: "",
    minConfidence: 0.78,
    maxGuideImages: 2,
    maxBytesPerImage: 10_485_760,
    imageTimeoutMs: 15_000,
    guideTimeoutMs: 45_000,
    modelTimeoutMs: 60_000,
    detail: "high",
    temperature: 0.1,
    maxTokens: 900,
    webSearch: {
      enabled: true,
      baseUrl: "",
      endpoint: "",
      apiKey: "",
      apiKeyEnv: "",
      model: "",
      timeoutMs: 25_000,
      maxResults: 5,
      allowedDomains: [],
      allowInsecureHttp: false,
      extraHeaders: {},
    },
  },
  routing: {
    topK: 12,
    maxInputChars: 2_000,
    autoExecuteEnabled: true,
    autoExecuteConfidence: 0.92,
    confirmConfidence: 0.65,
    minAutoRetrievalScore: 0.18,
    minAutoRetrievalMargin: 0.06,
  },
  commands: {
    enabledPresets: ["miao", "waves", "xiaoyao"],
    disabledIds: [],
    migrateLegacyAllowlist: true,
    autoExecuteAllowlist: [
      ...PRE_COMMAND_AUDIT_AUTO_EXECUTE_ALLOWLIST,
      ...COMMAND_AUDIT_AUTO_EXECUTE_IDS,
    ],
    custom: [],
  },
  memory: {
    enabled: true,
    ttlSeconds: 900,
    maxTurns: DEFAULT_MEMORY_TURNS,
    maxMessageChars: 1_000,
  },
  limits: {
    perUserRequests: 6,
    perUserWindowSeconds: 60,
    globalConcurrency: 3,
  },
  reply: {
    quote: true,
    useButtons: true,
    emptyPrompt: "你可以直接和我聊天，也可以告诉我想查询什么。",
    notConfigured: "AI 服务尚未配置，请主人设置 config/aiEnhance.yaml。",
    apiError: "AI 服务暂时不可用，请稍后再试。",
    imageError: "图片读取失败，请重新发送图片后再试。",
    visionDisabled: "当前未开启图片识别，请先在配置中启用 vision.enabled。",
    visionUnsupported:
      "当前模型或兼容 API 可能不支持图片输入，请更换支持视觉的模型后再试。",
    knowledgeUnavailable:
      "当前没有找到能可靠回答这个角色问题的攻略资料，我也没有可发送的攻略图。",
    tooLong: "消息太长了，请精简后再试。",
    busy: "当前请求较多，请稍后再试。",
    sensitive:
      "检测到消息可能包含 Token、Cookie 或密钥。为保护账号安全，这条消息不会发送给 AI，请在私聊中使用准确的原插件命令。",
  },
  logging: {
    decisions: true,
  },
}

export const LEGACY_DEFAULT_AUTO_EXECUTE_ALLOWLIST =
  PRE_COMMAND_AUDIT_AUTO_EXECUTE_ALLOWLIST.filter(
    id => !GUIDE_AUTO_EXECUTE_IDS.includes(id),
  )

export function cloneDefaults() {
  return structuredClone(DEFAULT_CONFIG)
}
