export const DEFAULT_CONFIG = {
  enabled: true,
  trigger: {
    privateEnabled: true,
    requireAtInGroup: true,
    allowAliasInGroup: true,
    enabledGroups: [],
    disabledGroups: [],
  },
  api: {
    baseUrl: "https://api.openai.com/v1",
    endpoint: "/chat/completions",
    apiKey: "",
    apiKeyEnv: "OPENAI_API_KEY",
    allowUnauthenticated: false,
    allowInsecureHttp: false,
    model: "",
    timeoutMs: 20_000,
    retries: 1,
    temperature: 0.2,
    maxTokens: 900,
    maxTokensField: "max_tokens",
    responseFormat: "auto",
    extraHeaders: {},
  },
  routing: {
    topK: 12,
    maxInputChars: 2_000,
    autoExecuteEnabled: true,
    autoExecuteConfidence: 0.92,
    confirmConfidence: 0.65,
    minAutoRetrievalScore: 0.18,
    minAutoRetrievalMargin: 0.06,
  },
  commands: {
    enabledPresets: ["miao", "waves", "xiaoyao"],
    disabledIds: [],
    autoExecuteAllowlist: [
      "miao.help",
      "miao.genshin_calendar",
      "miao.starrail_calendar",
      "miao.zzz_calendar",
      "miao.today_material",
      "miao.profile_list",
      "miao.profile_detail",
      "miao.profile_stats",
      "miao.gacha_summary",
      "miao.character_ownership",
      "miao.abyss_usage",
      "miao.abyss_teams",
      "miao.abyss_data",
      "miao.theater_data",
      "miao.stygian_data",
      "waves.help",
      "waves.login_help",
      "waves.sanity",
      "waves.card",
      "waves.explore",
      "waves.challenge",
      "waves.tower",
      "waves.profile",
      "waves.guide",
      "waves.atlas",
      "waves.calendar",
      "waves.news",
      "waves.gacha_records",
      "waves.data_bank",
      "waves.training",
      "waves.sign_records",
      "waves.redemption_codes",
      "waves.resource_report",
      "waves.character_ownership",
      "xiaoyao.help",
      "xiaoyao.version",
      "xiaoyao.stamina",
      "xiaoyao.atlas",
      "xiaoyao.map_location",
      "xiaoyao.account_help",
    ],
    custom: [],
  },
  memory: {
    enabled: true,
    ttlSeconds: 900,
    maxMessages: 8,
    maxMessageChars: 1_000,
  },
  limits: {
    perUserRequests: 6,
    perUserWindowSeconds: 60,
    globalConcurrency: 3,
  },
  reply: {
    quote: true,
    useButtons: true,
    emptyPrompt: "你可以直接和我聊天，也可以告诉我想查询什么。",
    notConfigured: "AI 服务尚未配置，请主人设置 config/aiEnhance.yaml。",
    apiError: "AI 服务暂时不可用，请稍后再试。",
    tooLong: "消息太长了，请精简后再试。",
    busy: "当前请求较多，请稍后再试。",
    sensitive:
      "检测到消息可能包含 Token、Cookie 或密钥。为保护账号安全，这条消息不会发送给 AI，请在私聊中使用准确的原插件命令。",
  },
  logging: {
    decisions: true,
  },
}

export function cloneDefaults() {
  return structuredClone(DEFAULT_CONFIG)
}
